apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30637
      protocol: TCP
    - name: cluster
      port: 16379
      targetPort: 16379
      nodePort: 31637
      protocol: TCP
  selector:
    app: redis-cluster
